---
title: "Science Communication Crash Course"
---

# Session 1 - 7/30/2024

## The "And, But, Therefore" Method

- Start the story with a few facts, setting out what the situation currently is. 

- Join these facts together with **AND** 

- Then something happens (or a problem is identified). 

- Introducing the word **BUT** indicates that this is the start of the real story. 

- This then leads to the action of the story, **THEREFORE**, where you set out the consequences of this problem and what you are going to do about it.

## Tips

**1. Consider your audience carefully**

When you read the following examples - you are the audience for these summaries. Do they include the 
key pieces of information you need to understand the research? Even if you don't understand all of the terms
used, do you get the gist of the project and why it's important? 

As you write your summary - who is your audience? What level of detail is appropriate, or necessary? 

**2. Strive for balance between simplicity and detail. **

These examples have varied amounts of detail. Some are more technical, some are more general. What level of detail is best for your study?

**3. Avoid jargon, technical terms not everyone knows, and abbreviations when possible**

Jargon, technical terms, and abbreviations increase the work the audience has to do to understand your work. Not only do they need to digest something fairly complex, but you're now also asking them to remember a new abbreviation or term. 

If you need to use a sentence to explain what a technical idea or term is, that can be ok! Better than assuming the audience already knows what you're talking about. 

**4. When you're done, step back and make sure your summary makes a step by step logical argument. **

Each new sentence needs to be supported by the previous ones and lead to the next sentence. If there is a break in the logic, it's harder for the audience to follow and understand your study. 

**5. Finally - read your paragraph *out loud* to yourself.**

It's much easier to catch errors or sentences that don't quite flow when you read it outloud. This keeps our brains from skipping over errors because we know what we meant to say.

## Examples

### Example 1:

Epilepsy affects 600,000 people in the UK AND is often treated using anti-epileptic drugs. BUT for 30% of people with epilepsy these drugs fail to control their seizures. THEREFORE scientists are looking at new types of treatment which will work better.

*What works, and what doesn't?*

### Example 2:  AI takes a turn:

The UK has a target to reduce carbon emissions by 80% by 2050 **AND** has made good progress in reducing emissions from electricity generation. **BUT** emissions from transport have not fallen. **THEREFORE** the government needs to take action to reduce emissions from cars and lorries.

### Example 3: Rob Cavanaugh (Roux Analyst)

Of the 800,000 people who have a stroke in the US every year, one third are diagnosed with aphasia, a language disorder that impairs our ability to communicate with our friends, familiy, and colleagues. 
**AND** Speech-Language Pathologists use standardized tests to assess language abilities in people with aphasia **BUT** these tests are often too time-consuming for routine clinical care and contain out-of-date and culturally insensitive stimuli. 
**THEREFORE**, our study will use computational modeling and item-response theory to develop and validate an efficient, adpative, and culturally sensitive language assessment for today's clinical practice.

### Example 4: Dr. Chelsea Wong, MD (T32 Postdoctoral Fellow)
 
Older sexual and gender minority adults face a higher burden of frailty as well as mental health issues **AND** frailty and mental health issues are risk factors for the use of potentially inappropriate medications. BUT the prevalence of potentially inappropriate medications is unknown among older sexual and gender minority adults. **THEREFORE,** it is critical to evaluate the use and adverse outcomes of potentially inappropriate medication use particularly in this population. In my study, I am assessing whether older sexual and gender minorit adults use a higher prevalence of potentially inappropriate medications compared to cisgender heterosexual older adults.

### Example 5: Dr. Louisa Smith (Roux, Bouve - Population Health)

Rural Maine has experienced a significant decline in obstetrics facilities, leading to decreased access to maternal healthcare. **AND** This decline is concerning as it correlates with poorer maternal and child health outcomes and increased travel times for essential care. **BUT** the challenges leading to rural obstetrics closures are not fully understood due to the diversity of the hospital settings. **THEREFORE**, we seek to identify key factors and develop targeted strategies to support and sustain the rural obstetrics workforce by conducting site visits and interviews with nurses, providers, and administrators at these locations.

Bisphosphonates are widely used to treat osteoporosis and other bone diseases, **AND** there is growing interest in their potential off-label effects, including the prevention of dementia. Observational studies have suggested a possible association between bisphosphonate use and reduced dementia risk, sparking significant scientific and public interest. **BUT** observational studies are prone to biases and confounding factors that can obscure the true causal relationship, making it challenging to determine whether bisphosphonates genuinely have a protective effect against dementia or if the observed associations are due to other factors. **THEREFORE** we are designing a target trial, which is the randomized controlled trial we would conduct in an ideal world, and will emulate it using observational data in order to rigorously assess the potential off-label effects of bisphosphonates on preventing dementia.

Maine's newly enacted paid family and medical leave law will provide support for working mothers to take time off from work after the birth of a child. **AND** Similar policies in other states have been shown to improve maternal mental health, breastfeeding practices, and postpartum care attendance. **BUT** no states with significant rural populations have implemented such a leave policy, so we lack understanding of how its effects on maternal health may differ between urban and rural populations. This gap hinders the ability to tailor policies to meet the unique needs of diverse populations. **THEREFORE** we are collecting data by surveying people around the state in their first year postpartum before and after the law goes into effect in order to inform policymakers and stakeholders on the effectiveness and adaptability of paid leave policies for varied populations.

### Example 6: Software development

The *All of Us* research program is a billion-dollar national effort to gather data from one million or more people living in the United States to accelerate research and precision medicine. The All of Us Research Program data is widely available to health researchers **BUT** using this data for complex research questions still requires a relatively high level of technical expertise, which poses a barrier to many researchers. **THEREFORE,** We developed the allofus R package to increase research and training capacity, reduce barriers to entry, and help researchers conduct complex analyses using best practices for reproducibility and transparency. 

### Dr. Paul Ayan (EAI)

The effective mitigation of the COVID-19 pandemic in the USA was challenged by unpredictable intervention outcomes due to a gap in integrating health, mobility, social behavior, and demographic data into models. **AND** Non-pharmaceutical interventions (NPIs) like lockdowns had adverse long-term effects and varied efficacy based on factors such as socioeconomic status (SES). **BUT** Current models either oversimplify transmission or lack socioeconomic factors, limiting their ability to understand the dynamics and effiveness of NPIs. **THEREFORE** we propose using detailed patient-level healthcare data and explainable AI (xAI) to better understand socioeconomic and behavioral predictors of disease spread. This approach will enhance Agent Based Models (ABMs), enabling more realistic simulations and effective mitigation strategies.

### Chloe Bennet (PhD Student, Population Health)

Diabetes affects 1 in 10 adults in the U.S. **AND** continuous glucose monitors (CGMs) significantly improve diabetes outcomes. **BUT** not everyone who uses a CGM will necessarily benefit equally. **THEREFORE** my study will use the Target Trials framework to estimate the causal effect of CGM use on racial disparities in type 2 diabetes outcomes.